In [3]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("aug_train.csv")
df.head(3)

enrollee_id      city  city_development_index gender  \
0         8949  city_103                   0.920   Male   
1        29725   city_40                   0.776   Male   
2        11561   city_21                   0.624    NaN   

       relevent_experience enrolled_university education_level  \
0  Has relevent experience       no_enrollment        Graduate   
1   No relevent experience       no_enrollment        Graduate   
2   No relevent experience    Full time course        Graduate   

  major_discipline experience company_size company_type last_new_job  \
0             STEM        >20          NaN          NaN            1   
1             STEM         15        50-99      Pvt Ltd           >4   
2             STEM          5          NaN          NaN        never   

   training_hours  target  
0              36     1.0  
1              47     0.0  
2              83     0.0

In [7]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64

In [15]:
 df.select_dtypes(include="object").isnull().sum()

city                      0
gender                 4508
relevent_experience       0
enrolled_university     386
education_level         460
major_discipline       2813
experience               65
company_size           5938
company_type           6140
last_new_job            423
dtype: int64

In [19]:
 df.select_dtypes(include="object").columns

Index(['city', 'gender', 'relevent_experience', 'enrolled_university',
       'education_level', 'major_discipline', 'experience', 'company_size',
       'company_type', 'last_new_job'],
      dtype='object')

In [23]:
for i in  df.select_dtypes(include="object").columns:
    df[i].fillna(df[i].mode()[0])

In [29]:
data=df[["enrolled_university"]]

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
one = OneHotEncoder()

In [35]:
one.fit_transform(data)

<19158x3 sparse matrix of type '<class 'numpy.float64'>'
	with 19158 stored elements in Compressed Sparse Row format>

In [39]:
array=one.fit_transform(data).toarray()

In [41]:
# lable Encoding

dt=pd.DataFrame({"name":["cow","cat","dog","Fox","box"]})

In [43]:
dt

name
0  cow
1  cat
2  dog
3  Fox
4  box

In [45]:
from sklearn.preprocessing import LabelEncoder

In [47]:
la= LabelEncoder()

In [51]:
dt["name2"]=la.fit_transform(dt["name"])

In [55]:
dt

name  name2
0  cow      3
1  cat      2
2  dog      4
3  Fox      0
4  box      1

In [59]:
le=LabelEncoder()

In [61]:
le.fit(df["enrolled_university"])

LabelEncoder()

In [63]:
le.transform(df["enrolled_university"])

array([2, 2, 0, ..., 2, 2, 2])

In [65]:
df["enrolled_university"].unique()

array(['no_enrollment', 'Full time course', 'Part time course'],
      dtype=object)

In [67]:
df["enrolled_university"]=le.transform(df["enrolled_university"])

In [69]:
df["enrolled_university"].unique()

array([2, 0, 1])

In [89]:
# ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

dtp=pd.DataFrame({"size":["s","m","l","xl","xxl"]})

In [91]:
dtp

size
0    s
1    m
2    l
3   xl
4  xxl

In [93]:
dp=[["s","m","l","xl","xxl"]]

In [109]:
na=OrdinalEncoder(categories=dp)

In [113]:
na.fit(dtp[["size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl', 'xxl']])

In [121]:
na.transform(dtp[["size"]])

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]])

In [123]:
dtp["size_en"]=na.transform(dtp[["size"]])

In [125]:
dtp

size  size_en
0    s      0.0
1    m      1.0
2    l      2.0
3   xl      3.0
4  xxl      4.0

In [135]:
# through map function
ord1={"s":5,"m":4,"l":3,"xl":2,"xxl":1}

In [137]:
dtp["size_enn"]=dtp["size"].map(ord1)

In [139]:
dtp

size  size_en  size_enn
0    s      0.0         5
1    m      1.0         4
2    l      2.0         3
3   xl      3.0         2
4  xxl      4.0         1

In [3]:
import pandas as pd
data=pd.read_csv("aug_train.csv")
data.head(3)

enrollee_id      city  city_development_index gender  \
0         8949  city_103                   0.920   Male   
1        29725   city_40                   0.776   Male   
2        11561   city_21                   0.624    NaN   

       relevent_experience enrolled_university education_level  \
0  Has relevent experience       no_enrollment        Graduate   
1   No relevent experience       no_enrollment        Graduate   
2   No relevent experience    Full time course        Graduate   

  major_discipline experience company_size company_type last_new_job  \
0             STEM        >20          NaN          NaN            1   
1             STEM         15        50-99      Pvt Ltd           >4   
2             STEM          5          NaN          NaN        never   

   training_hours  target  
0              36     1.0  
1              47     0.0  
2              83     0.0

In [5]:
data.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64

In [9]:
data["gender"].fillna(data["gender"].mode()[0])

0        Male
1        Male
2        Male
3        Male
4        Male
         ... 
19153    Male
19154    Male
19155    Male
19156    Male
19157    Male
Name: gender, Length: 19158, dtype: object

In [11]:
data.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                       0
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64

In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [57]:
data["relevent_experience"].unique()


array(['Has relevent experience', 'No relevent experience'], dtype=object)

In [59]:
gene=[["Has relevent experience","Has relevent experience"]]

In [67]:
genee=OrdinalEncoder()

In [69]:
genee.fit(data[["relevent_experience"]])

OrdinalEncoder()

In [75]:
data["relevent_experience"]=genee.transform(data[["relevent_experience"]])

In [77]:
data.head(3)

enrollee_id      city  city_development_index gender  relevent_experience  \
0         8949  city_103                   0.920   Male                  0.0   
1        29725   city_40                   0.776   Male                  1.0   
2        11561   city_21                   0.624   Male                  1.0   

  enrolled_university education_level major_discipline experience  \
0       no_enrollment        Graduate             STEM        >20   
1       no_enrollment        Graduate             STEM         15   
2    Full time course        Graduate             STEM          5   

  company_size company_type last_new_job  training_hours  target  
0          NaN          NaN            1              36     1.0  
1        50-99      Pvt Ltd           >4              47     0.0  
2          NaN          NaN        never              83     0.0

In [79]:
import seaborn as sns
import matplotlib.pyplot as plt

In [81]:
datas=pd.read_csv("aug_train.csv")
datas.head(3)

enrollee_id      city  city_development_index gender  \
0         8949  city_103                   0.920   Male   
1        29725   city_40                   0.776   Male   
2        11561   city_21                   0.624    NaN   

       relevent_experience enrolled_university education_level  \
0  Has relevent experience       no_enrollment        Graduate   
1   No relevent experience       no_enrollment        Graduate   
2   No relevent experience    Full time course        Graduate   

  major_discipline experience company_size company_type last_new_job  \
0             STEM        >20          NaN          NaN            1   
1             STEM         15        50-99      Pvt Ltd           >4   
2             STEM          5          NaN          NaN        never   

   training_hours  target  
0              36     1.0  
1              47     0.0  
2              83     0.0

In [83]:
datas.describe()

enrollee_id  city_development_index  training_hours        target
count  19158.000000            19158.000000    19158.000000  19158.000000
mean   16875.358179                0.828848       65.366896      0.249348
std     9616.292592                0.123362       60.058462      0.432647
min        1.000000                0.448000        1.000000      0.000000
25%     8554.250000                0.740000       23.000000      0.000000
50%    16982.500000                0.903000       47.000000      0.000000
75%    25169.750000                0.920000       88.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

In [95]:
sns.boxplot( "enrollee_id",data=datas)
plt.show()

TypeError: boxplot() got multiple values for argument 'data'